---
title: "R Notebook"
output:
  html_notebook: default
  html_document: default
  pdf_document: default
---

## Loading and pre-processing data

```{r}

#Loading and pre-processing data

setwd('E:/SageDocs/PredictingDriverGenes/LineageMisc/')

Dat <- read.delim('MAYO_CBE_TCX_logCPM.tsv',stringsAsFactors = F)
Dat2 <- read.delim('MAYO_CBE_TCX_Covariates.tsv',stringsAsFactors = F)

AMP_mods <-  read.csv('TCX_AMPAD_Modules.csv')

GeneNames <- Dat$ensembl_gene_id
GeneNamesAD <- AMP_mods$GeneID

Names <- colnames(Dat)

for (i in 1:length(Names)){
  
  Names[i] <- substring(Names[i],2)
  
}

colnames(Dat) <- Names
cNames <- Dat2$SampleID
l <- length(Names)

#deleting columns not in the covariate list 
for (i in 1:l){
  if (!(Names[i] %in% cNames)){
    Dat[,i] <- NULL
  }
}


#Normalize all columns 
source('MiscPreprocessing.R')

DatNorm <- ColNorm(Dat)
In <- which(GeneNames %in% GeneNamesAD)
DatNorm2 <- DatNorm[In,]
library(Rtsne)
Temp <- Rtsne(t(DatNorm2))


```


## Visualizing the whole dataset using tSNE

```{r}

#tSNE visualization for whole dataset
plot(Temp$Y[,1],Temp$Y[,2], col = as.factor(Dat2$Sex))

```


## Visualizing the one brain region using tSNE


```{r}

#Keeping only TCX data 
In_BR <- grep('TCX',Dat2$Tissue.Diagnosis)
DatNorm3 <- DatNorm2[,In_BR]
Dat3 <- Dat2[In_BR,]
Temp <- Rtsne(t(DatNorm3))
plot(Temp$Y[,1],Temp$Y[,2], col = as.factor(Dat3$Sex))

```




## Performing lineage inference using Monocle2


```{r}

#Performing lineage inference with Monocle2
source('LineageFunctions.R')
temp <- DatNorm3
rownames(temp) <- NULL
colnames(temp) <- NULL
MonRun <- RunMonocleTobit(temp, Dat3$AgeAtDeath)


```

## Visualizing using Monocle's visualization 

```{r}

plot_cell_trajectory(MonRun, color_by = "Labels")

```



## Visualizing Monocle2 with different labels 

```{r}

Monocle.Plot(MonRun, Labels = Dat3$Tissue.Diagnosis.Sex, Discrete = T)


```

## Viewing gene expression overlaid on the lineage 

```{r}

gList <- GeneNames[In]
g <- GeneNames[In[1]]
  
Mon.Plot.Genes(MonRun, DatNorm3, gList, g)


```

