#install dependencies and programs for AMPAD_Lineage
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("Biobase", "BiocGenerics","DelayedArray","DelayedMatrixStats","limma","S4Vectors","SingleCellExperiment","SummarizedExperiment", "batchelor","edgeR","qvalue", "multtest"))
install.packages("boot")
install.packages("foreign")
install.packages("MASS")
install.packages("nlme")
install.packages("Rfast")
install.packages("rqdatatable")

install.packages("synapser", repos=c("http://ran.synapse.org", "http://cran.fhcrc.org"))
devtools::install_url('https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.7.tar.gz')
devtools::install_github('cole-trapnell-lab/leidenbase')
devtools::install_github('cole-trapnell-lab/monocle3')
BiocManager::install("biomaRt")
library(synapser)
synLogin()
library(monocle3)
library(biomaRt)
library(rqdatatable)
library(Matrix)
